openapi: 3.1.0
info:
  title: azuki-api
  version: "0.1"
  summary: github.com/sylms/azuki api document
servers: []
paths:
  /course:
    get:
      summary: /course
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/course"
          headers: {}
      operationId: get-course
      parameters:
        - schema:
            type: string
            example: course_name="情報 生物"
          in: query
          name: course_name
          description: 科目名。半角・全角スペース区切りで単語分割。
        - schema:
            type: string
            example: course_overview="情報 生物"
          in: query
          name: course_overview
          description: 科目概要。半角・全角スペース区切りで単語分割。
        - schema:
            type: string
            enum:
              - and
              - or
            example: course_name_filter_type=and
          in: query
          name: course_name_filter_type
          description: "`course_name` の各単語をどのように繋げて検索するか。"
        - schema:
            type: string
            enum:
              - and
              - or
            example: course_overview_filter_type=and
          in: query
          name: course_overview_filter_type
          description: "`course_overview` の各単語をどのように繋げて検索するか。"
        - schema:
            type: string
            enum:
              - and
              - or
            example: filter_type=and
          in: query
          name: filter_type
          description: 各要素のどのように繋げて検索するか。現在は、何と指定しようが、AND で結ばれて検索される。
      description: |
        科目を検索します。

        例えば、`course_name` に「情報」と指定した場合、科目名に「情報」を含む科目の情報を返します。
        `course_name` と `course_overview` のどちらかはクエリにつける必要があります。
components:
  schemas:
    course:
      title: course
      type: object
      description: WIP
      examples:
        - id: 18080
          course_number: GB13312
          course_name: 情報特別演習I
          instructional_type: 2
          credits: "2.0"
          standard_registration_year: null
          term: null
          period: null
          classroom: null
          instructor: null
          course_overview: "受講生の自主的なテーマ設定および解法設計を重視した演習を行う。発案力,実現力,表現力を養うことを目的とする。"
          remarks: 情報科学類生に限る。 オンライン(オンデマンド型) オンライン(同時双方向型) 対面
          credited_auditors: 0
          application_conditions: 施設設備の許容量上の制約と学類生に対する良質の少人数教育を行うため
          alt_course_name: Special Exercise in Information Science I
          course_code: GB13312
          course_code_name: 情報特別演習I
          csv_updated_at: "2021-03-23T11:43:50+09:00"
          year: 2021
          created_at: "2021-08-24T00:42:18.517476+09:00"
          updated_at: "2021-08-24T00:42:18.517476+09:00"
      properties:
        id:
          type: integer
          example: 101
        course_number:
          type: string
          example: GB13312
        course_name:
          type: string
          example: 情報特別演習I
        instructional_type:
          type: number
          example: 2
        credits:
          type: string
          example: "2.0"
        standard_registration_year:
          type: array
          items:
            type: integer
            example: "[2]"
        period:
          type: array
          items:
            type: string
            example: 随時
        classroom:
          type:
            - string
            - "null"
        instructor:
          type: array
          items:
            type: string
        course_overview:
          type:
            - string
            - "null"
          example: "受講生の自主的なテーマ設定および解法設計を重視した演習を行う。発案力,実現力,表現力を養うことを目的とする。"
        remarks:
          type:
            - string
            - "null"
          example: 情報科学類生に限る。 オンライン(オンデマンド型) オンライン(同時双方向型) 対面
        credited_auditors:
          type: integer
          example: 0
        application_conditions:
          type:
            - string
            - "null"
          example: 施設設備の許容量上の制約と学類生に対する良質の少人数教育を行うため
        alt_course_name:
          type:
            - string
            - "null"
          example: Special Exercise in Information Science I
        course_code:
          type:
            - string
            - "null"
          example: GB13312
        course_code_name:
          type:
            - string
            - "null"
          example: 情報特別演習I
        csv_updated_at:
          type: string
          example: "2021-03-23 11:43:50+09"
        year:
          type: integer
          example: 2021
        created_at:
          type: string
          example: "2021-08-24 00:42:18.517476+09"
        updated_at:
          type: string
          example: "2021-08-24 00:42:18.517476+09"
  parameters: {}
  responses: {}
