openapi: 3.0.3
info:
  title: azuki-api
  version: "0.1"
  description: github.com/sylms/azuki api document
servers: []
paths:
  /course:
    post:
      summary: /course
      tags: ["course"]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                title: courses
                items:
                  $ref: "#/components/schemas/course"
          headers: {}
        "400":
          description: Bad Request
      operationId: get-course
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:  
                course_name:
                  type: string
                  example: "情報 生物"
                  description: 科目名。半角・全角スペース区切りで単語分割。
                course_overview:
                  type: string
                  example: "情報 生物"
                  description: 科目概要。半角・全角スペース区切りで単語分割。
                course_name_filter_type:
                  type: string
                  enum:
                    - and
                    - or
                  example: and
                  description: "`course_name` の各単語をどのように繋げて検索するか。`course_name` を設定しているときにはこのパラメーターも必須である。"
                course_overview_filter_type:
                  type: string
                  enum:
                    - and
                    - or
                  example: and
                  description: "`course_overview` の各単語をどのように繋げて検索するか。`course_overview` を設定しているときにはこのパラメーターも必須である。"
                filter_type:
                  type: string
                  enum:
                    - and
                    - or
                  example: and
                  description: 各要素のどのように繋げて検索するか。現在は、何と指定しようが、AND で結ばれて検索される。
                limit:
                  type: integer
                  example: 10
                  default: 100
                  description: 取得する最大件数
                offset:
                  type: integer
                  example: 10
                  default: 0
                  description: スキップする件数
      description: |
        科目を検索します。

        例えば、`course_name` に「情報」と指定した場合、科目名に「情報」を含む科目の情報を返します。
        `course_name` と `course_overview` のどちらかはクエリにつける必要があります。
components:
  schemas:
    course:
      title: course
      type: object
      properties:
        id:
          type: integer
          example: 101
          description: "通し番号である。"
        course_number:
          type: string
          example: GB13312
          description: "科目番号である。"
        course_name:
          type: string
          example: 情報特別演習I
          description: "科目名である。"
        instructional_type:
          type: number
          example: 2
          description: "授業方法である。値は https://www.tsukuba.ac.jp/education/ug-courses-openclass/2021/pdf/1.pdf#page=2 を参照すること。"
        credits:
          type: string
          example: "2.0"
          description: "単位数である。KdB のデータをそのまま保持しており「-」が含まれることがある。"
        standard_registration_year:
          type: array
          items:
            type: integer
            example: "[2]"
          description: "標準履修年次である。KdB のデータをほぼそのまま保持しており「?」が含まれることがある。"
        term:
          type: array
          nullable: true
          items:
            type: integer
            example: "[2]"
          description: |
            開講時期である。数値と具体的な時期の対応は以下の通りである。

            春A = 1

            春B = 2

            春C = 3

            秋A = 4

            秋B = 5

            秋C = 6

            夏季休業中 = 7

            春季休業中 = 8

            通年 = 9

            春学期 = 10

            秋学期 = 11
        period:
          type: array
          items:
            type: string
            example: 随時
          description: "曜時限である。"
        classroom:
          type: string
          nullable: true
          description: "教室である。"
        instructor:
          type: array
          items:
            type: string
          description: "担当教員である。"
        course_overview:
          type: string
          nullable: true
          example: "受講生の自主的なテーマ設定および解法設計を重視した演習を行う。発案力,実現力,表現力を養うことを目的とする。"
          description: "授業概要である。"
        remarks:
          type: string
          nullable: true
          example: 情報科学類生に限る。 オンライン(オンデマンド型) オンライン(同時双方向型) 対面
          description: "備考である。"
        credited_auditors:
          type: integer
          example: 0
          description: "科目等履修生申請可否である。対応は、「×」は 0、「△」は 1、空は 2 となっている。"
        application_conditions:
          type: string
          nullable: true
          example: 施設設備の許容量上の制約と学類生に対する良質の少人数教育を行うため
          description: "申請条件である。"
        alt_course_name:
          type: string
          nullable: true
          example: Special Exercise in Information Science I
          description: "英語(日本語)科目名である。"
        course_code:
          type: string
          nullable: true
          example: GB13312
          description: "科目コードである。"
        course_code_name:
          type: string
          nullable: true
          example: 情報特別演習I
          description: "要件科目名である。"
        csv_updated_at:
          type: string
          example: "2021-03-23 11:43:50+09"
          description: "KdB からエクスポートした CSV ファイルに記載されている「データ更新日」である。"
        year:
          type: integer
          example: 2021
          description: "対象年度である。"
        created_at:
          type: string
          example: "2021-08-24 00:42:18.517476+09"
          description: "azuki が参照する DB 上のデータの作成日時である。"
        updated_at:
          type: string
          example: "2021-08-24 00:42:18.517476+09"
          description: "azuki が参照する DB 上のデータの更新日時である。"
      example:
        - id: 18080
          course_number: GB13312
          course_name: 情報特別演習I
          instructional_type: 2
          credits: "2.0"
          standard_registration_year: null
          term: null
          period: null
          classroom: null
          instructor: null
          course_overview: "受講生の自主的なテーマ設定および解法設計を重視した演習を行う。発案力,実現力,表現力を養うことを目的とする。"
          remarks: 情報科学類生に限る。 オンライン(オンデマンド型) オンライン(同時双方向型) 対面
          credited_auditors: 0
          application_conditions: 施設設備の許容量上の制約と学類生に対する良質の少人数教育を行うため
          alt_course_name: Special Exercise in Information Science I
          course_code: GB13312
          course_code_name: 情報特別演習I
          csv_updated_at: "2021-03-23T11:43:50+09:00"
          year: 2021
          created_at: "2021-08-24T00:42:18.517476+09:00"
          updated_at: "2021-08-24T00:42:18.517476+09:00"
  parameters: {}
  responses: {}
